dist: trusty
language: java
sudo: required
services:
- docker
jdk:
- oraclejdk8
install: true
env:
- GROUP=ronniek COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=queue-master;
script:
- set -e
- "./scripts/build.sh;"
- "./test/test.sh unit.py"
- "./test/test.sh component.py"
after_success:
- set -e;
- "travis_wait ./test/test.sh coveralls.py"
- if [ -z "$DOCKER_PASS" ] ; then echo "This is a build triggered by an external PR.
  Skipping docker push."; exit 0; fi;
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
- "./scripts/push.sh"
notifications:
  webhooks: https://api.opsgenie.com/v1/json/travisci?apiKey=41caacf0-fc8f-42c0-94cd-4891ddd27bcf
